#7/17/2026
#Interpreter 3.10.6 64bit
#This is the body program for the information lookup program
#The attached C program needs to be executed first, BOTH programs likely need path modifications
#The two "load" programs are what actually get called, generate_subject_paths connects to backend C program.
#This rendition directly takes user input and print matches instead of passing them. 
#Modifying this to receive and pass to input and output only needs changing in main function.
#***JSON FILES GET SAVED TO DEFAULT PATHWAY, NOT PROGRAM FOLDER PATH***

import subprocess
import json
import re

pathstarting = "/home/pmoney/"
pathending = "_paths.json"
dynamicpath = ""

verbs = []
agitators = []
glo_list = []
subjects = []
sub = ""
ver = ""
agi = ""

def generate_subject_paths(subject):
    c_program = "/home/pathwayto/backend.c"
  #***NEEDS CHANGES

    try:
        result = subprocess.run([c_program, subject], capture_output=True, text=True,check=True)
        print(result.stdout)

    except subprocess.CalledProcessError as e:
        print("High Level Backend Failure in Information Part: ", c_program)
        print(e.stderr)

    except FileNotFoundError:
        print("High Level Backend for Information Part Not Found. Check the program path: ", c_program)
    #Both except statements are just error handling, aren't really necessary

def return_user_subject(sentence):
    global glo_list
    words = sentence.split()

    for word in words:
        if sentence not in glo_list: 
            if word.lower() != subjects and word.lower() != verbs and word.lower() != agitators:
                glo_list.append(sentence)
                break
            else:
                glo_list.insert(0, sentence)
#Inserts sentence matching original user syntax in the front of list of subjects

def parse_data(twodlist, sentences):
    temp_list = []

    for path in twodlist:
        total_terms = len(path)

        for sentence in sentences:
            matches = 0

            for term in path:
                if term.lower() in sentence.lower():
                    matches += 1

            if total_terms == 0:
                continue

            match_percent = matches / total_terms

            if match_percent >= 0.80:
                #0.80 means 80% threshold for path and source term matches
                temp_list.append((sentence, matches))
                return_user_subject(sentence)

#This is the more important function of the program
#All it does it cut up source words and compare against paths one by one
#Used for decision making on pathways against sources

    unique = {}

    for sentence, matches in temp_list:
        if sentence not in unique or matches > unique[sentence]:
            unique[sentence] = matches

    temp_list = [(sentence, matches) for sentence, matches in unique.items()]
#Checks if the source was already placed in the list, otherwise we would have duplicates

def load_prereqs(uinput):
    global subjects, verbs, agitators, sub, ver, agi
    temp_sub = uinput
    subj = ""
    words = temp_sub.split()
    with open("/home/pathwayto/subjects.txt") as file1:
        #***NEEDS CHANGES
      
        sdata = file1.read()
    subjects  = [line.strip().lower() for line in sdata.splitlines() if line.strip()]

    with open("/home/pathway/verbs.txt") as file2:
        #***NEEDS CHANGES

        vdata = file2.read()
    verbs = [line.strip().lower() for line in vdata.splitlines() if line.strip()]

    with open("/home/pathwayto/agitators.txt") as file3:
        #***NEEDS CHANGES

        adata = file3.read()
    agitators  = [line.strip().lower() for line in adata.splitlines() if line.strip()]

    for word in words:
        if word in subjects:
            sub = word
            subj = word
        elif word in verbs:
            ver = word
        elif word in agitators:
            agi = word
    #This loop right here can be removed!

    generate_subject_paths(subj)
#Handles file opening of terms and designates subject, verb, and agitator of user input
#Can remove marked loop if this is handled elsewhere before being passed to this function

def load_to_py():
    global sub
    dynamicpath = (pathstarting + sub + pathending)
    with open(dynamicpath, "r", encoding="utf-8") as file:
        data = json.load(file)
    
    twodlist = data["paths"]
    #cuts up json file in paths, json file generated by backend

    with open("/home/pathwayto/large_sources.txt") as file:
        #***NEEDS CHANGES

        ldata = file.read()
    sentences = [s.strip() for s in re.split(r'(?<=[.!?])[\s\n\r]+', ldata) if s.strip()]

    parse_data(twodlist, sentences)
    #cuts out large sources
#Cuts up words in json file made from C backend, and cuts up sentences of sources file

if __name__ == "__main__":
    uinput = input("Enter subject: ")
    #This can be changed if passed input from elsewhere
    load_prereqs(uinput)
    load_to_py()
    print(glo_list)
    #the above print statement can be removed if connected to another program
